### ISSUE TITLE
Error while implementing the code

### ISSUE THREAD

**Issue by LRafea** [QodeMaster/Code_Solutions#1]
Thanks a lot for you posting Codesignal codes!

But I'm trying to implement the first snippet which is "centuryFromYear" and I got this error in Codesignal

System.NullReferenceException: Object reference not set to an instance of an object.
   at TestingCSharp.TEST_0.run() in main.cs in the pre-written template

Could you please advice!

**Comment by QodeMaster** [comment]
CodeSignal made an update some time ago where every function that returns the answer was renamed to 'solution'.
To fix the issue just rename `int centuryFromYear(int year) {...}` to `int solution(int year) {...}`.

**Comment by LRafea** [comment]
Thanks a lot for following up!

Issue has been solved.

Best,
Layth


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
